import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AthleteAppContextProvider } from "@/context/AthleteAppContext";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AthleteAppContextProvider>
          <div className="flex flex-col h-screen">
            <Toaster/>
            <Header />
            <div className="flex flex-1 pt-14">
              <Sidebar />
              <main className="flex-1 p-5 overflow-y-auto ml-0 md:ml-60 bg-[#fcf8ea]">
                {children}
              </main>
            </div>
          </div>
        </AthleteAppContextProvider>
      </body>
    </html>
  );
}
